version: '3.0'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - testnet
    command: 
    - "--providers.consulcatalog=true"
    - "--providers.consulcatalog.endpoint.address=consul:80"
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--log.level=DEBUG"
    ports:
      - 8080:80
      - 8081:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    volumes:
      - ./consul_cfg:/etc/consul
    ports:
      - 3210:80
    command: agent -server -dev -enable-script-checks -ui -node=server -bind=0.0.0.0 -config-dir=/etc/consul -client=0.0.0.0 -http-port=80
    networks:
      - testnet
  webapp:
    image: testapp
    container_name: webapp
    depends_on:
      - traefik
    networks:
      - testnet
    environment:
      - PORT=3001
      - "APP_ID=test app1"
  webapp2:
    image: testapp
    container_name: webapp2
    depends_on:
      - traefik
    networks:
      - testnet
    environment:
      - PORT=3001
      - "APP_ID=test app2"

networks:
  testnet:
    driver: bridge
    external: true
