version: '3.0'

services:
  haproxyapp:
    image: haproxy:latest
    ports:
      - 3000:8080
      - 9999:9999
    volumes:
      - ./test.cfg:/usr/local/etc/haproxy/haproxy.cfg
  app1:
    image: testapp
    environment:
      - PORT=3001
      - APP_ID="test app1"
  app2:
    image: testapp
    environment:
      - PORT=3001
      - APP_ID="test app2"
  app3:
    image: testapp
    environment:
      - PORT=3001
      - APP_ID="test app3"

      # echo "<h2>hello server 1</h2>" > index.html